CREATE TABLE [aut].[Client]
(
	[ClientId] UNIQUEIDENTIFIER CONSTRAINT [DF_ClientId] DEFAULT NEWID() NOT NULL,
	[Name] NVARCHAR(1024) NOT NULL,
	[CreateTimestamp] DATETIME2(4) CONSTRAINT [DF_Client_CreateTimestamp] DEFAULT(SYSUTCDATETIME()) NOT NULL,
	[UpdateTimestamp] DATETIME2(4) CONSTRAINT [DF_Client_UpdateTimestamp] DEFAULT(SYSUTCDATETIME()) NOT NULL,
	CONSTRAINT [PK_Client] PRIMARY KEY CLUSTERED ([ClientId])
)
