CREATE TABLE [yl].[Project]
(
	[ProjectId] UNIQUEIDENTIFIER NOT NULL,
	[Title] NVARCHAR(750) NOT NULL,
	[CreateTimestamp] DATETIME2(4) CONSTRAINT [DF_Project_CreateTimestamp] DEFAULT (SYSUTCDATETIME()) NOT NULL,
	[UpdateTimestamp] DATETIME2(4) CONSTRAINT [DF_Project_UpdateTimestamp] DEFAULT (SYSUTCDATETIME()) NOT NULL,
	CONSTRAINT [PK_Project] PRIMARY KEY CLUSTERED ([ProjectId])
)
WITH (DATA_COMPRESSION = PAGE)
