CREATE TABLE [yl].[WorkItem_Comment]
(
	[WorkItemId] UNIQUEIDENTIFIER NOT NULL,
	[CommentId] UNIQUEIDENTIFIER NOT NULL,
	[Type] SMALLINT NOT NULL,
	[CreateTimestamp] DATETIME2(4) CONSTRAINT [DF_WorkItem_Comment_CreateTimestamp] DEFAULT (SYSUTCDATETIME()) NOT NULL,
	CONSTRAINT [PK_WorkItem_Comment] PRIMARY KEY CLUSTERED ([WorkItemId], [CommentId])
)
